/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Cliente;
import Datos.DatosParcela;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Jacques
 */
public class Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    private Cliente cliente;
    private JFrame vistaAnterior;
    private ArrayList<Object> parcelasSeleccionadas = new ArrayList<Object>();
    private ArrayList<String> nombresTiendas = new ArrayList<String>();
    private ArrayList<Integer> metrosTiendas = new ArrayList<Integer>();
    private JRadioButton[] radiobutton = new JRadioButton[37];
    private boolean reserva;
    
    public Reserva(boolean reserva) {
        
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Reservas");
        this.reserva = reserva;
        
        //Seleccion del radioButton de la Luz
        grupo_botones_luz.add(luzSi);
        grupo_botones_luz.add(luzNO);
        fEntrada.enable(reserva);
        btn_finalizar.setVisible(false);
        
        for(int i = 1; i < 38; i++){
            radiobutton[i] = new JRadioButton(""+i);
            botonesParcelas.add(radiobutton[i]);
        }
        
        /*
        for(Object item: cliente.consultarParcelas()){
            combo_parcelas.addItem(item);
        }
        Object parcela = combo_parcelas.getSelectedItem();
        DatosParcela datosParcela = cliente.consultarDatosParcela(parcela);
        lbl_metrosparcela.setText(Integer.toString(datosParcela.metrosCuadrados));
        lbl_precioParcela.setText(Integer.toString(datosParcela.precioDia));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        grupo_botones_luz = new javax.swing.ButtonGroup();
        mapaParcelas = new javax.swing.JFrame();
        btn_cancelarMapa = new javax.swing.JButton();
        btn_guardarParcela = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        botonesParcelas = new javax.swing.ButtonGroup();
        lbl_nomape = new javax.swing.JLabel();
        nombreyApellidos = new javax.swing.JTextField();
        lbl_dni = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        lbl_fechentrada = new javax.swing.JLabel();
        fEntrada = new datechooser.beans.DateChooserCombo();
        fSalida = new datechooser.beans.DateChooserCombo();
        lbl_mcuadrados = new javax.swing.JLabel();
        mTienda = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        tipoTienda = new javax.swing.JTextField();
        luzSi = new javax.swing.JRadioButton();
        luzNO = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_luzparcela = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_finalizar = new javax.swing.JButton();
        lbl_fechasalida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        btn_seleccParcelas = new javax.swing.JButton();

        mapaParcelas.setSize(new java.awt.Dimension(920, 610));
        mapaParcelas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cancelarMapa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cancelarMapa.setText("Cancelar");
        btn_cancelarMapa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cancelarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarMapaActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(btn_cancelarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 200, 40));

        btn_guardarParcela.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_guardarParcela.setText("Guardar Parcela");
        btn_guardarParcela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_guardarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarParcelaActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(btn_guardarParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 200, 40));
        mapaParcelas.getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 20, -1));

        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 20, -1));
        mapaParcelas.getContentPane().add(jRadioButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/mapa.png"))); // NOI18N
        jLabel1.setOpaque(true);
        mapaParcelas.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nomape.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nomape.setText("Nombre y Apellidos:");
        getContentPane().add(lbl_nomape, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 30));

        nombreyApellidos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        nombreyApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreyApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(nombreyApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 30));

        lbl_dni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_dni.setText("DNI:");
        getContentPane().add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 50, 30));

        DNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DNI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, 30));

        lbl_fechentrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechentrada.setText("Fecha de entrada:");
        getContentPane().add(lbl_fechentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 150, 40));
        getContentPane().add(fEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, 40));
        getContentPane().add(fSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, 40));

        lbl_mcuadrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_mcuadrados.setText("Metros cuadrados:");
        getContentPane().add(lbl_mcuadrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 160, 30));

        mTienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(mTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 150, 30));

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, 30));

        tipoTienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tipoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 30));

        luzSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luzSi.setText("Si");
        luzSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzSiActionPerformed(evt);
            }
        });
        getContentPane().add(luzSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 80, 30));

        luzNO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luzNO.setText("No");
        luzNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzNOActionPerformed(evt);
            }
        });
        getContentPane().add(luzNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Introduzca sus datos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Introduzca los detalles de su tienda de campaña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 410, 20));

        lbl_luzparcela.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_luzparcela.setText("¿Desea contar con servicio de luz en su parcela ?");
        getContentPane().add(lbl_luzparcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 410, 30));

        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 140, 40));

        btn_finalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_finalizar.setText("Finalizar");
        btn_finalizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 140, 40));

        lbl_fechasalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechasalida.setText("Fecha de salida:");
        getContentPane().add(lbl_fechasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 140, 40));

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mis parcelas reservadas:"));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 290, 120));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 410, 20));

        btn_seleccParcelas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_seleccParcelas.setText("Seleccionar Parcela");
        btn_seleccParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_seleccParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccParcelasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seleccParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luzNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzNOActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
        Principal prin = new Principal();
        prin.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        try{
            //Guardamos los datos en variables auxiliares
            String nombreApellidos = nombreyApellidos.getText();
            String dni = DNI.getText();
            String nombreTienda = tipoTienda.getText();
            int metrosTienda = Integer.parseInt(mTienda.getText());
            boolean luz = false;
            if(luzSi.isSelected())
                luz = true;
            Date fechaIni = fEntrada.getSelectedDate().getTime();

            Date fechaFin = fSalida.getSelectedDate().getTime();
            cliente.reserva(nombreApellidos, dni, nombresTiendas, metrosTiendas, luz,
                    fechaIni, fechaFin, parcelasSeleccionadas);
            
        }   
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en alguno de los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_finalizarActionPerformed

    private void mTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTiendaActionPerformed

    private void luzSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzSiActionPerformed

    private void btn_seleccParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccParcelasActionPerformed
        this.setVisible(false);
        mapaParcelas.setVisible(true);
        
    }//GEN-LAST:event_btn_seleccParcelasActionPerformed

    private void btn_cancelarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarMapaActionPerformed
                                                           
        this.setVisible(true);
        mapaParcelas.setVisible(false);
    }//GEN-LAST:event_btn_cancelarMapaActionPerformed

    private void btn_guardarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarParcelaActionPerformed
                                                           
        this.setVisible(true);
        mapaParcelas.setVisible(false);
        btn_finalizar.setVisible(true);
        //guardar parcela seleccionada
        
    }//GEN-LAST:event_btn_guardarParcelaActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNI;
    private javax.swing.ButtonGroup botonesParcelas;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelarMapa;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_guardarParcela;
    private javax.swing.JButton btn_seleccParcelas;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserCombo fEntrada;
    private datechooser.beans.DateChooserCombo fSalida;
    private javax.swing.ButtonGroup grupo_botones_luz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fechasalida;
    private javax.swing.JLabel lbl_fechentrada;
    private javax.swing.JLabel lbl_luzparcela;
    private javax.swing.JLabel lbl_mcuadrados;
    private javax.swing.JLabel lbl_nomape;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JRadioButton luzNO;
    private javax.swing.JRadioButton luzSi;
    private javax.swing.JTextField mTienda;
    private javax.swing.JFrame mapaParcelas;
    private javax.swing.JTextField nombreyApellidos;
    private javax.swing.JTextField tipoTienda;
    // End of variables declaration//GEN-END:variables
}
