/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Gerente;
import Controlador.GestoresCamping;
import Datos.DatosParcela;
import Datos.DatosReserva;
import Datos.ListaParcelas;
import Datos.ListaReservas;
import Datos.ListasEventos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anita
 */
public class VistaGerente extends javax.swing.JFrame {

    private JFrame vistaAnterior;
    private Gerente gerente;
    private GestoresCamping gestoresCamping;
    private String parejaAct;
    DefaultListModel lReservas;
    DefaultListModel lPiscina;
    DefaultListModel lFronton;
    DefaultListModel lClub;
    DefaultListModel lPiscinaParejas;
    DefaultListModel lFrontonParejas;
    DefaultListModel lClubParejas;
    DefaultListModel lPiscinaGanador;
    DefaultListModel lFrontonGanador;
    DefaultListModel lClubGanador;
    DefaultListModel lParcelas;
    DefaultTableModel tParcelas;
    private boolean tramite;

    /**
     * Creates new form Gerente
     *
     * @param vistaAnterior
     * @param gerente
     */
    public VistaGerente(JFrame vistaAnterior, Gerente gerente) {
        super("Gerentes");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tramite = false;
        panelPago.setVisible(tramite);
        this.gerente = gerente;
        this.vistaAnterior = vistaAnterior;
        this.setTitle("Administración Gerente");
        btnPiscina.setOpaque(false);
        btnFronton.setOpaque(false);
        btnClubSocial.setOpaque(false);
        parejaAct = "";
        
        // Actualizamos la lista de reservas
        lReservas = new DefaultListModel();
        listaReservas.setModel(lReservas);

        for (Object item : this.gerente.consultarReserva()) {
            lReservas.addElement(item);
        }
        
        actualizarEventos();
        
        lPiscinaParejas = new DefaultListModel();
        lParejasPiscina.setModel(lPiscinaParejas);
        lPiscinaGanador = new DefaultListModel();
        lGanadoresPiscina.setModel(lPiscinaGanador);
        
        lFrontonParejas = new DefaultListModel();
        lParejasFronton.setModel(lFrontonParejas);
        lFrontonGanador = new DefaultListModel();
        lGanadoresFronton.setModel(lFrontonGanador);
        
        lClubParejas = new DefaultListModel();
        lParejasClub.setModel(lClubParejas);
        lClubGanador = new DefaultListModel();
        lGanadoresClub.setModel(lClubGanador);
        
        descuentoAct.setText(String.valueOf(this.gerente.getDescuento()));
        
    }
    
    public void actualizarEventos(){
        // Pedimos las listas de los usuarios suscritos a eventos
        ListasEventos le = this.gerente.listasEventos();
        
        // Actualizamos la lista del evento PISCINA
        lPiscina = new DefaultListModel();
        lUsuariosPiscina.setModel(lPiscina);
        for(Object item: le.listaPiscina)
            lPiscina.addElement(item);
        lUsuariosPiscina.updateUI();
        
        // Actualizamos la lista del evento CLUB
        lClub = new DefaultListModel();
        lUsuariosClub.setModel(lClub);
        for(Object item: le.listaClub)
            lClub.addElement(item);
        lUsuariosClub.updateUI();
        
        // Actualizamos la lista del evento FRONTON
        lFronton = new DefaultListModel();
        lUsuariosFronton.setModel(lFronton);
        for(Object item: le.listaFronton)
            lFronton.addElement(item);
        lUsuariosFronton.updateUI();
    } 
         
    
    public void resetReservas(){
        tramite = false;
        panelPago.setVisible(tramite);
        fSalida.enable(true);
        fEntrada.enable(true);
        fSalida.setVisible(true);
        listaParcelas.enable(true);
        botonGuardarReserva.setText("Guardar");
        botonGuardarReserva.updateUI();
        botonTramitar.setVisible(true);
        fondobotones15.setVisible(true);
        botonTramitar.enable(true);
        
    }
    public void actualizarVista(){
        // Actualizamos la lista de reservas
        lReservas = new DefaultListModel();
        listaReservas.setModel(lReservas);
        
        for (Object item : this.gerente.consultarReserva()) {
            lReservas.addElement(item);
        }
        
        listaReservas.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventos = new javax.swing.JFrame();
        panelFronton = new javax.swing.JPanel();
        btn_sancionarFronton = new javax.swing.JButton();
        fondobotones11 = new javax.swing.JLabel();
        btn_emparejarFronton = new javax.swing.JButton();
        fondobotones12 = new javax.swing.JLabel();
        btn_ganadorFronton = new javax.swing.JButton();
        fondobotones13 = new javax.swing.JLabel();
        jScrollPane8Fronton = new javax.swing.JScrollPane();
        lUsuariosFronton = new javax.swing.JList<>();
        jScrollPane9Fronton = new javax.swing.JScrollPane();
        lParejasFronton = new javax.swing.JList<>();
        jScrollPane10Fronton = new javax.swing.JScrollPane();
        lGanadoresFronton = new javax.swing.JList<>();
        titulo = new javax.swing.JLabel();
        fondo4 = new javax.swing.JLabel();
        panelPiscina = new javax.swing.JPanel();
        btn_sancionarPiscina = new javax.swing.JButton();
        fondobotones8 = new javax.swing.JLabel();
        btn_emparejarPiscina = new javax.swing.JButton();
        fondobotones9 = new javax.swing.JLabel();
        btn_ganadorPiscina = new javax.swing.JButton();
        fondobotones10 = new javax.swing.JLabel();
        jScrollPane5Piscina = new javax.swing.JScrollPane();
        lUsuariosPiscina = new javax.swing.JList<>();
        jScrollPane6Piscina = new javax.swing.JScrollPane();
        lParejasPiscina = new javax.swing.JList<>();
        jScrollPane7Piscina = new javax.swing.JScrollPane();
        lGanadoresPiscina = new javax.swing.JList<>();
        titulo1 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();
        panelClubSocial = new javax.swing.JPanel();
        btn_sancionar = new javax.swing.JButton();
        fondobotones6 = new javax.swing.JLabel();
        btn_emparejar = new javax.swing.JButton();
        fondobotones5 = new javax.swing.JLabel();
        btn_ganador = new javax.swing.JButton();
        fondobotones7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lUsuariosClub = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lParejasClub = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lGanadoresClub = new javax.swing.JList<>();
        titulo2 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        btn_atras2 = new javax.swing.JButton();
        fondobotones4 = new javax.swing.JLabel();
        lbl_iniciosesion = new javax.swing.JLabel();
        btnPiscina = new javax.swing.JButton();
        btnFronton = new javax.swing.JButton();
        btnClubSocial = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        reservas = new javax.swing.JFrame();
        panelPago = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaparcelas = new javax.swing.JTable();
        lbtotal = new javax.swing.JLabel();
        lbparcelas = new javax.swing.JLabel();
        lbdias = new javax.swing.JLabel();
        lbrallitas = new javax.swing.JLabel();
        lbdescuento = new javax.swing.JLabel();
        lbparcelas1 = new javax.swing.JLabel();
        lbdias1 = new javax.swing.JLabel();
        lbtotal1 = new javax.swing.JLabel();
        fondo6 = new javax.swing.JLabel();
        lbl_nomape = new javax.swing.JLabel();
        nombreyApellidos = new javax.swing.JTextField();
        lbl_dni = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        lbl_fechentrada = new javax.swing.JLabel();
        fEntrada = new datechooser.beans.DateChooserCombo();
        fSalida = new datechooser.beans.DateChooserCombo();
        jlabeldatosreserva = new javax.swing.JLabel();
        lbl_fechasalida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaParcelas = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        lbl_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        txt_cp = new javax.swing.JTextField();
        lbl_cp = new javax.swing.JLabel();
        botonAtrasReserva = new javax.swing.JButton();
        fondobotones14 = new javax.swing.JLabel();
        botonGuardarReserva = new javax.swing.JButton();
        fondobotones16 = new javax.swing.JLabel();
        botonTramitar = new javax.swing.JButton();
        fondobotones15 = new javax.swing.JLabel();
        idReserva = new javax.swing.JLabel();
        fondo5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_administrar = new javax.swing.JButton();
        fondobotones2 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        fondobotones = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        fondobotones1 = new javax.swing.JLabel();
        scroll_parcelas = new javax.swing.JScrollPane();
        listaReservas = new javax.swing.JList<>();
        scroll_eventos = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        btn_descuento = new javax.swing.JButton();
        fondobotones3 = new javax.swing.JLabel();
        des = new javax.swing.JLabel();
        descuentoAct = new javax.swing.JLabel();
        xcien = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        eventos.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        eventos.setTitle("Administrar Eventos");
        eventos.setLocation(new java.awt.Point(265, 112));
        eventos.setMinimumSize(new java.awt.Dimension(1000, 600));
        eventos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFronton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sancionarFronton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_sancionarFronton.setText("Sancionar");
        btn_sancionarFronton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_sancionarFronton.setContentAreaFilled(false);
        btn_sancionarFronton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sancionarFrontonActionPerformed(evt);
            }
        });
        panelFronton.add(btn_sancionarFronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        fondobotones11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones11.setText("jLabel2");
        panelFronton.add(fondobotones11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        btn_emparejarFronton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_emparejarFronton.setText("Emparejar");
        btn_emparejarFronton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_emparejarFronton.setContentAreaFilled(false);
        btn_emparejarFronton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emparejarFrontonActionPerformed(evt);
            }
        });
        panelFronton.add(btn_emparejarFronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

        fondobotones12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones12.setText("jLabel2");
        panelFronton.add(fondobotones12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

        btn_ganadorFronton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_ganadorFronton.setText("Ganador");
        btn_ganadorFronton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ganadorFronton.setContentAreaFilled(false);
        btn_ganadorFronton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ganadorFrontonActionPerformed(evt);
            }
        });
        panelFronton.add(btn_ganadorFronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 40));

        fondobotones13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones13.setText("jLabel2");
        panelFronton.add(fondobotones13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 40));

        lUsuariosFronton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lUsuariosFronton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lUsuariosFronton.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8Fronton.setViewportView(lUsuariosFronton);

        panelFronton.add(jScrollPane8Fronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 77, 140, 184));

        lParejasFronton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parejas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lParejasFronton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lParejasFronton.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9Fronton.setViewportView(lParejasFronton);

        panelFronton.add(jScrollPane9Fronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 77, 140, 184));

        lGanadoresFronton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ganador/es", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lGanadoresFronton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lGanadoresFronton.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10Fronton.setViewportView(lGanadoresFronton);

        panelFronton.add(jScrollPane10Fronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 77, 139, 93));

        titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo.setText("Fronton");
        panelFronton.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 70));

        fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelFronton.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -130, -1, -1));

        eventos.getContentPane().add(panelFronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 710, 370));

        panelPiscina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sancionarPiscina.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_sancionarPiscina.setText("Sancionar");
        btn_sancionarPiscina.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_sancionarPiscina.setContentAreaFilled(false);
        btn_sancionarPiscina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sancionarPiscinaActionPerformed(evt);
            }
        });
        panelPiscina.add(btn_sancionarPiscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        fondobotones8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones8.setText("jLabel2");
        panelPiscina.add(fondobotones8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        btn_emparejarPiscina.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_emparejarPiscina.setText("Emparejar");
        btn_emparejarPiscina.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_emparejarPiscina.setContentAreaFilled(false);
        btn_emparejarPiscina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emparejarPiscinaActionPerformed(evt);
            }
        });
        panelPiscina.add(btn_emparejarPiscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

        fondobotones9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones9.setText("jLabel2");
        panelPiscina.add(fondobotones9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

        btn_ganadorPiscina.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_ganadorPiscina.setText("Ganador");
        btn_ganadorPiscina.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ganadorPiscina.setContentAreaFilled(false);
        btn_ganadorPiscina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ganadorPiscinaActionPerformed(evt);
            }
        });
        panelPiscina.add(btn_ganadorPiscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 40));

        fondobotones10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones10.setText("jLabel2");
        panelPiscina.add(fondobotones10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 40));

        lUsuariosPiscina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lUsuariosPiscina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lUsuariosPiscina.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5Piscina.setViewportView(lUsuariosPiscina);

        panelPiscina.add(jScrollPane5Piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 77, 140, 184));

        lParejasPiscina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parejas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lParejasPiscina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lParejasPiscina.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6Piscina.setViewportView(lParejasPiscina);

        panelPiscina.add(jScrollPane6Piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 77, 140, 184));

        lGanadoresPiscina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ganador/es", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lGanadoresPiscina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lGanadoresPiscina.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7Piscina.setViewportView(lGanadoresPiscina);

        panelPiscina.add(jScrollPane7Piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 77, 139, 93));

        titulo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo1.setText("Piscina");
        panelPiscina.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 70));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPiscina.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -130, -1, -1));

        eventos.getContentPane().add(panelPiscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 710, 370));

        panelClubSocial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sancionar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_sancionar.setText("Sancionar");
        btn_sancionar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_sancionar.setContentAreaFilled(false);
        btn_sancionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sancionarActionPerformed(evt);
            }
        });
        panelClubSocial.add(btn_sancionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        fondobotones6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones6.setText("jLabel2");
        panelClubSocial.add(fondobotones6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        btn_emparejar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_emparejar.setText("Emparejar");
        btn_emparejar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_emparejar.setContentAreaFilled(false);
        btn_emparejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emparejarActionPerformed(evt);
            }
        });
        panelClubSocial.add(btn_emparejar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

        fondobotones5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones5.setText("jLabel2");
        panelClubSocial.add(fondobotones5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

        btn_ganador.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_ganador.setText("Ganador");
        btn_ganador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ganador.setContentAreaFilled(false);
        btn_ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ganadorActionPerformed(evt);
            }
        });
        panelClubSocial.add(btn_ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 40));

        fondobotones7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones7.setText("jLabel2");
        panelClubSocial.add(fondobotones7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 40));

        lUsuariosClub.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lUsuariosClub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lUsuariosClub.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lUsuariosClub);

        panelClubSocial.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 77, 140, 184));

        lParejasClub.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parejas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lParejasClub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lParejasClub.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lParejasClub);

        panelClubSocial.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 77, 140, 184));

        lGanadoresClub.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ganador/es", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 0, 14))); // NOI18N
        lGanadoresClub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lGanadoresClub.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lGanadoresClub);

        panelClubSocial.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 77, 139, 93));

        titulo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo2.setText("Club Social");
        panelClubSocial.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 70));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelClubSocial.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -130, -1, -1));

        eventos.getContentPane().add(panelClubSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 710, 370));

        btn_atras2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_atras2.setText("Atrás");
        btn_atras2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_atras2.setContentAreaFilled(false);
        btn_atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atras2ActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btn_atras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, 40));

        fondobotones4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones4.setText("jLabel2");
        eventos.getContentPane().add(fondobotones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, 40));

        lbl_iniciosesion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_iniciosesion.setText("Seleccione un evento");
        eventos.getContentPane().add(lbl_iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 350, 30));

        btnPiscina.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnPiscina.setText("PISCINA");
        btnPiscina.setBorder(null);
        btnPiscina.setBorderPainted(false);
        btnPiscina.setContentAreaFilled(false);
        btnPiscina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiscinaActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btnPiscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 229, 175, 63));

        btnFronton.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnFronton.setText("FRONTON");
        btnFronton.setBorder(null);
        btnFronton.setBorderPainted(false);
        btnFronton.setContentAreaFilled(false);
        btnFronton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrontonActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btnFronton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, 175, 63));

        btnClubSocial.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnClubSocial.setText("CLUB SOCIAL");
        btnClubSocial.setBorder(null);
        btnClubSocial.setBorderPainted(false);
        btnClubSocial.setContentAreaFilled(false);
        btnClubSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClubSocialActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btnClubSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 175, 63));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eventos.getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        reservas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaparcelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaparcelas.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tablaparcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Parcela", "Precio/Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaparcelas.setShowHorizontalLines(false);
        jScrollPane5.setViewportView(tablaparcelas);

        panelPago.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 435, 93));

        lbtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbtotal.setText("TOTAL");
        panelPago.add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 236, 71, -1));

        lbparcelas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbparcelas.setText(" Parcelas");
        panelPago.add(lbparcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 80, -1));

        lbdias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbdias.setText("Días");
        panelPago.add(lbdias, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 179, 48, -1));

        lbrallitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbrallitas.setText("------------------------");
        panelPago.add(lbrallitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 202, -1));

        lbdescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbdescuento.setText("DESCUENTO     ");
        panelPago.add(lbdescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 160, 170, -1));

        lbparcelas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelPago.add(lbparcelas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 143, 63, -1));

        lbdias1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelPago.add(lbdias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 179, 63, 25));

        lbtotal1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelPago.add(lbtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 236, -1, 25));

        fondo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPago.add(fondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -50, -1, -1));

        reservas.getContentPane().add(panelPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 460, 440));

        lbl_nomape.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nomape.setText("Nombre y Apellidos:");
        reservas.getContentPane().add(lbl_nomape, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 30));

        nombreyApellidos.setEditable(false);
        nombreyApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreyApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reservas.getContentPane().add(nombreyApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, 30));

        lbl_dni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_dni.setText("DNI:");
        reservas.getContentPane().add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, 30));

        txt_dni.setEditable(false);
        txt_dni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_dni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reservas.getContentPane().add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 180, 30));

        lbl_fechentrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechentrada.setText("Fecha de entrada:");
        reservas.getContentPane().add(lbl_fechentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 150, 40));

        fEntrada.setCalendarPreferredSize(new java.awt.Dimension(317, 321));
        reservas.getContentPane().add(fEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 190, 40));
        reservas.getContentPane().add(fSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 190, 40));

        jlabeldatosreserva.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jlabeldatosreserva.setText("Datos de la Reserva");
        reservas.getContentPane().add(jlabeldatosreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 40));

        lbl_fechasalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechasalida.setText("Fecha de salida:");
        reservas.getContentPane().add(lbl_fechasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 140, 40));

        listaParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas reservadas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        listaParcelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listaParcelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaParcelas);

        reservas.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 360, 150));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reservas.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 410, 20));

        lbl_tel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tel.setText("Telefono: ");
        reservas.getContentPane().add(lbl_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 100, 30));

        txt_tel.setEditable(false);
        txt_tel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        reservas.getContentPane().add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 30));

        lbl_correo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_correo.setText("Correo: ");
        reservas.getContentPane().add(lbl_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 100, 30));

        txt_correo.setEditable(false);
        txt_correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_correo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        reservas.getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, 30));

        txt_cp.setEditable(false);
        txt_cp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpActionPerformed(evt);
            }
        });
        reservas.getContentPane().add(txt_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 180, 30));

        lbl_cp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_cp.setText("Codigo Postal: ");
        reservas.getContentPane().add(lbl_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 140, 30));

        botonAtrasReserva.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        botonAtrasReserva.setText("Atras");
        botonAtrasReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonAtrasReserva.setContentAreaFilled(false);
        botonAtrasReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasReservaActionPerformed(evt);
            }
        });
        reservas.getContentPane().add(botonAtrasReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 120, 40));

        fondobotones14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones14.setText("jLabel2");
        reservas.getContentPane().add(fondobotones14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 120, 40));

        botonGuardarReserva.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        botonGuardarReserva.setText("Guardar");
        botonGuardarReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonGuardarReserva.setContentAreaFilled(false);
        botonGuardarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarReservaActionPerformed(evt);
            }
        });
        reservas.getContentPane().add(botonGuardarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 520, 120, 40));

        fondobotones16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones16.setText("jLabel2");
        reservas.getContentPane().add(fondobotones16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 120, 40));

        botonTramitar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        botonTramitar.setText("Tramitar el pago");
        botonTramitar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonTramitar.setContentAreaFilled(false);
        botonTramitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTramitarActionPerformed(evt);
            }
        });
        reservas.getContentPane().add(botonTramitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 220, 40));

        fondobotones15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones15.setText("jLabel2");
        reservas.getContentPane().add(fondobotones15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 220, 40));

        idReserva.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        reservas.getContentPane().add(idReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 30, 44, 40));

        fondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reservas.getContentPane().add(fondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_administrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_administrar.setText("Administrar");
        btn_administrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_administrar.setContentAreaFilled(false);
        btn_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 110, 30));

        fondobotones2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones2.setText("jLabel2");
        getContentPane().add(fondobotones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 110, 30));

        btn_atras.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_atras.setText("Atrás");
        btn_atras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_atras.setContentAreaFilled(false);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 140, 40));

        fondobotones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones.setText("jLabel2");
        getContentPane().add(fondobotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 140, 40));

        btn_modificar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_modificar.setText("Administrar");
        btn_modificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_modificar.setContentAreaFilled(false);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, 30));

        fondobotones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones1.setText("jLabel2");
        getContentPane().add(fondobotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, 30));

        listaReservas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        listaReservas.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Reserva 1", "Reserva 2", "Reserva 3", "Reserva 4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scroll_parcelas.setViewportView(listaReservas);

        getContentPane().add(scroll_parcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 430, 220));

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eventos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Piscina", "Fronton", "Club Social" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scroll_eventos.setViewportView(jList3);

        getContentPane().add(scroll_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 430, 220));

        btn_descuento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_descuento.setText("Actualizar");
        btn_descuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_descuento.setContentAreaFilled(false);
        btn_descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descuentoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 110, 40));

        fondobotones3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones3.setText("jLabel2");
        getContentPane().add(fondobotones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 110, 40));

        des.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        des.setText("El descuento aplicable es de un ");
        getContentPane().add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, 20));

        descuentoAct.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().add(descuentoAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 30, 20));

        xcien.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        xcien.setText("%");
        getContentPane().add(xcien, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 30, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazul.png"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administrarActionPerformed
        eventos.setSize(1000, 600);
        eventos.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_administrarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        this.setVisible(false);
        gestoresCamping = new GestoresCamping();
        vistaAnterior.setVisible(true);
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (listaReservas.getSelectedValue() != null) {
            // Ponemos los datos de la reserva en vista
            DatosReserva dr = gerente.datosReserva(listaReservas.getSelectedValue());
            nombreyApellidos.setText(dr.nombreApellidos);
            txt_dni.setText(dr.dni);
            txt_tel.setText(dr.telefono);
            txt_correo.setText(dr.correo);
            txt_cp.setText(dr.cp);
            
            Date fecha = dr.fechaIni;
            fecha.setHours(0);
            fecha.setMinutes(0);
            Calendar cal = Calendar.getInstance();
            cal.setTime(fecha);
            fEntrada.setSelectedDate(cal);
            
            fecha = dr.fechaFin;
            fecha.setHours(0);
            fecha.setMinutes(0);
            cal = Calendar.getInstance();
            cal.setTime(fecha);
            fSalida.setSelectedDate(cal);
            
            lParcelas = new DefaultListModel();
            listaParcelas.setModel(lParcelas);
            for(Object parcela: dr.parcelasSeleccionadas){
                lParcelas.addElement(parcela);
            }
            
            // Cambiamos de frame a reserva
            reservas.setSize(1000, 600);
            Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (int) ((dimension.getWidth() - reservas.getWidth()) / 2);
            int y = (int) ((dimension.getHeight() - reservas.getHeight()) / 2);
            reservas.setLocation(x, y);
            reservas.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una reserva.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atras2ActionPerformed
        eventos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btn_atras2ActionPerformed

    private void btn_sancionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sancionarActionPerformed
        JOptionPane.showMessageDialog(null, "El usuario "+lUsuariosClub.getSelectedValue()+" ha sido sancionado", "Sancion", 0);
        gerente.sancionarClienteClub(lUsuariosClub.getSelectedValue());
        lClub.removeElement(lUsuariosClub.getSelectedValue());
        lUsuariosClub.updateUI();
    }//GEN-LAST:event_btn_sancionarActionPerformed

    private void btn_emparejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emparejarActionPerformed
    parejaAct = (JOptionPane.showInputDialog(null, "El usuario "+lUsuariosClub.getSelectedIndex()+" pertenece a la pareja: ", "Emparejar", JOptionPane.QUESTION_MESSAGE));
        if ("".equals(parejaAct)) {
            parejaAct = "0";
            lClubParejas.addElement(lUsuariosClub.getSelectedValue() + " " + parejaAct);
        }
        else{
            lClubParejas.addElement(lUsuariosClub.getSelectedValue() + " " + parejaAct);
        }
        lParejasClub.updateUI();
        lClub.remove(lUsuariosClub.getSelectedIndex());
    }//GEN-LAST:event_btn_emparejarActionPerformed

    private void btn_ganadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ganadorActionPerformed
        //setGanador;
    }//GEN-LAST:event_btn_ganadorActionPerformed

    private void btn_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descuentoActionPerformed
       descuentoAct.setText(JOptionPane.showInputDialog(null, "Introduce el descuento que quiere aplicar: ", "Descuento", JOptionPane.QUESTION_MESSAGE));
        if ("".equals(descuentoAct.getText())) {
            descuentoAct.setText(" 0");
        }
        gerente.setDescuento(Integer.parseInt(descuentoAct.getText()));
    }//GEN-LAST:event_btn_descuentoActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpActionPerformed

    private void botonAtrasReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasReservaActionPerformed
        this.setVisible(true);
        reservas.setVisible(false);
        
        actualizarVista();
        resetReservas();
    }//GEN-LAST:event_botonAtrasReservaActionPerformed

    private void botonGuardarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarReservaActionPerformed
        if(!tramite)
            gerente.actualizarFechaReserva(fEntrada.getSelectedDate().getTime(), fSalida.getSelectedDate().getTime());
        else
            gerente.tramitarReserva();
        
        actualizarVista();
        this.setVisible(true);
        reservas.setVisible(false);
        resetReservas();
    }//GEN-LAST:event_botonGuardarReservaActionPerformed

    private void botonTramitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTramitarActionPerformed
        tramite = true;
        panelPago.setVisible(tramite);
        fSalida.enable(false);
        fEntrada.enable(false);
        fSalida.setVisible(false);
        listaParcelas.enable(false);
        botonGuardarReserva.setText("Finalizar");
        botonGuardarReserva.updateUI();
        botonTramitar.setVisible(false);
        fondobotones15.setVisible(false);
        botonTramitar.enable(false);
        
        // Guardamos las parcelas y sus precios en una tabla
        DatosReserva dr = gerente.datosReserva(listaReservas.getSelectedValue());
        tParcelas = new DefaultTableModel();
        tablaparcelas.setModel(tParcelas);
        tParcelas.addColumn("Parcelas", new Vector<>(dr.parcelasSeleccionadas));
        tParcelas.addColumn("Precio/dia", new Vector<>(dr.precioParcelas));
        
        // Calculamos los dias que ha estado y el precio de la estancia
        lbparcelas1.setText(""+ gerente.getPrecioReserva());
        lbparcelas1.updateUI();
        lbdias1.setText(""+gerente.getDias());
        lbdias1.updateUI();
        
            lbtotal1.setText("" + gerente.getPrecioTotal());
            lbtotal1.updateUI();
        
    }//GEN-LAST:event_botonTramitarActionPerformed

    private void btnPiscinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiscinaActionPerformed
        panelClubSocial.setVisible(false);
        panelPiscina.setVisible(true);
        panelFronton.setVisible(false);
        
        panelClubSocial.setEnabled(false);
        panelPiscina.setEnabled(true);
        panelFronton.setEnabled(false);
    }//GEN-LAST:event_btnPiscinaActionPerformed

    private void btnFrontonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrontonActionPerformed
        panelClubSocial.setVisible(false);
        panelPiscina.setVisible(false);
        panelFronton.setVisible(true);
        
        panelClubSocial.setEnabled(false);
        panelPiscina.setEnabled(false);
        panelFronton.setEnabled(true);
    }//GEN-LAST:event_btnFrontonActionPerformed

    private void btnClubSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClubSocialActionPerformed
        panelClubSocial.setVisible(true);
        panelPiscina.setVisible(false);
        panelFronton.setVisible(false);
        
        panelClubSocial.setEnabled(true);
        panelPiscina.setEnabled(false);
        panelFronton.setEnabled(false);
    }//GEN-LAST:event_btnClubSocialActionPerformed

    private void btn_sancionarPiscinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sancionarPiscinaActionPerformed
        JOptionPane.showMessageDialog(null, "El usuario "+lUsuariosPiscina.getSelectedValue()+" ha sido sancionado", "Sancion", 0);
        gerente.sancionarClientePiscina(lUsuariosPiscina.getSelectedValue());
        lPiscina.removeElement(lUsuariosPiscina.getSelectedValue());
        lUsuariosPiscina.updateUI();
    }//GEN-LAST:event_btn_sancionarPiscinaActionPerformed

    private void btn_emparejarPiscinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emparejarPiscinaActionPerformed
    parejaAct = (JOptionPane.showInputDialog(null, "El usuario "+lUsuariosPiscina.getSelectedIndex()+" pertenece a la pareja: ", "Emparejar", JOptionPane.QUESTION_MESSAGE));
        if ("".equals(parejaAct)) {
            parejaAct = "0";
            lPiscinaParejas.addElement(lUsuariosPiscina.getSelectedValue() + " " + parejaAct);
        }
        else{
            lPiscinaParejas.addElement(lUsuariosPiscina.getSelectedValue() + " " + parejaAct);
        }
        lParejasPiscina.updateUI();
        lPiscina.remove(lUsuariosPiscina.getSelectedIndex());
    }//GEN-LAST:event_btn_emparejarPiscinaActionPerformed

    private void btn_ganadorPiscinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ganadorPiscinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ganadorPiscinaActionPerformed

    private void btn_sancionarFrontonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sancionarFrontonActionPerformed
        JOptionPane.showMessageDialog(null, "El usuario "+lUsuariosFronton.getSelectedValue()+" ha sido sancionado", "Sancion", 0);
        gerente.sancionarClienteFronton(lUsuariosFronton.getSelectedValue());
        lFronton.removeElement(lUsuariosFronton.getSelectedValue());
        lUsuariosFronton.updateUI();
    }//GEN-LAST:event_btn_sancionarFrontonActionPerformed

    private void btn_emparejarFrontonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emparejarFrontonActionPerformed
    parejaAct = (JOptionPane.showInputDialog(null, "El usuario "+lUsuariosFronton.getSelectedIndex()+" pertenece a la pareja: ", "Emparejar", JOptionPane.QUESTION_MESSAGE));
        if ("".equals(parejaAct)) {
            parejaAct = "0";
            lFrontonParejas.addElement(lUsuariosFronton.getSelectedValue() + " " + parejaAct);
        }
        else{
            lFrontonParejas.addElement(lUsuariosFronton.getSelectedValue() + " " + parejaAct);
        }
        lParejasFronton.updateUI();
        lFronton.remove(lUsuariosFronton.getSelectedIndex());
        
    }//GEN-LAST:event_btn_emparejarFrontonActionPerformed

    private void btn_ganadorFrontonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ganadorFrontonActionPerformed
        JOptionPane.showMessageDialog(null, "El usuario "+lUsuariosFronton.getSelectedValue()+" es un ganador.");
        lFrontonGanador.addElement(lUsuariosFronton.getSelectedValue());
        lGanadoresFronton.updateUI();
    }//GEN-LAST:event_btn_ganadorFrontonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasReserva;
    private javax.swing.JButton botonGuardarReserva;
    private javax.swing.JButton botonTramitar;
    private javax.swing.JButton btnClubSocial;
    private javax.swing.JButton btnFronton;
    private javax.swing.JButton btnPiscina;
    private javax.swing.JButton btn_administrar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_atras2;
    private javax.swing.JButton btn_descuento;
    private javax.swing.JButton btn_emparejar;
    private javax.swing.JButton btn_emparejarFronton;
    private javax.swing.JButton btn_emparejarPiscina;
    private javax.swing.JButton btn_ganador;
    private javax.swing.JButton btn_ganadorFronton;
    private javax.swing.JButton btn_ganadorPiscina;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_sancionar;
    private javax.swing.JButton btn_sancionarFronton;
    private javax.swing.JButton btn_sancionarPiscina;
    private javax.swing.JLabel des;
    private javax.swing.JLabel descuentoAct;
    private javax.swing.JFrame eventos;
    private datechooser.beans.DateChooserCombo fEntrada;
    private datechooser.beans.DateChooserCombo fSalida;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JLabel fondo5;
    private javax.swing.JLabel fondo6;
    private javax.swing.JLabel fondobotones;
    private javax.swing.JLabel fondobotones1;
    private javax.swing.JLabel fondobotones10;
    private javax.swing.JLabel fondobotones11;
    private javax.swing.JLabel fondobotones12;
    private javax.swing.JLabel fondobotones13;
    private javax.swing.JLabel fondobotones14;
    private javax.swing.JLabel fondobotones15;
    private javax.swing.JLabel fondobotones16;
    private javax.swing.JLabel fondobotones2;
    private javax.swing.JLabel fondobotones3;
    private javax.swing.JLabel fondobotones4;
    private javax.swing.JLabel fondobotones5;
    private javax.swing.JLabel fondobotones6;
    private javax.swing.JLabel fondobotones7;
    private javax.swing.JLabel fondobotones8;
    private javax.swing.JLabel fondobotones9;
    private javax.swing.JLabel idReserva;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10Fronton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane5Piscina;
    private javax.swing.JScrollPane jScrollPane6Piscina;
    private javax.swing.JScrollPane jScrollPane7Piscina;
    private javax.swing.JScrollPane jScrollPane8Fronton;
    private javax.swing.JScrollPane jScrollPane9Fronton;
    private javax.swing.JLabel jlabeldatosreserva;
    private javax.swing.JList<String> lGanadoresClub;
    private javax.swing.JList<String> lGanadoresFronton;
    private javax.swing.JList<String> lGanadoresPiscina;
    private javax.swing.JList<String> lParejasClub;
    private javax.swing.JList<String> lParejasFronton;
    private javax.swing.JList<String> lParejasPiscina;
    private javax.swing.JList<Object> lUsuariosClub;
    private javax.swing.JList<Object> lUsuariosFronton;
    private javax.swing.JList<Object> lUsuariosPiscina;
    private javax.swing.JLabel lbdescuento;
    private javax.swing.JLabel lbdias;
    private javax.swing.JLabel lbdias1;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fechasalida;
    private javax.swing.JLabel lbl_fechentrada;
    private javax.swing.JLabel lbl_iniciosesion;
    private javax.swing.JLabel lbl_nomape;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbparcelas;
    private javax.swing.JLabel lbparcelas1;
    private javax.swing.JLabel lbrallitas;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JLabel lbtotal1;
    private javax.swing.JList<Object> listaParcelas;
    private javax.swing.JList<Object> listaReservas;
    private javax.swing.JTextField nombreyApellidos;
    private javax.swing.JPanel panelClubSocial;
    private javax.swing.JPanel panelFronton;
    private javax.swing.JPanel panelPago;
    private javax.swing.JPanel panelPiscina;
    private javax.swing.JFrame reservas;
    private javax.swing.JScrollPane scroll_eventos;
    private javax.swing.JScrollPane scroll_parcelas;
    private javax.swing.JTable tablaparcelas;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JLabel xcien;
    // End of variables declaration//GEN-END:variables
}
