/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Gerente;
import Controlador.GestoresCamping;
import Datos.DatosParcela;
import Datos.ListaParcelas;
import Datos.ListaReservas;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anita
 */
public class VistaGerente extends javax.swing.JFrame {

    private JFrame vistaAnterior;
    private Gerente gerente;
    private GestoresCamping gestoresCamping;

    DefaultListModel lReservas;

    /**
     * Creates new form Gerente
     *
     * @param vistaAnterior
     * @param gerente
     */
    public VistaGerente(JFrame vistaAnterior, Gerente gerente) {
        super("Gerentes");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        gerente = gerente;
        vistaAnterior = vistaAnterior;
        this.setTitle("Administración Gerente");

        lReservas = new DefaultListModel();
        listaReservas.setModel(lReservas);

        ListaReservas lr = gerente.consultarReserva();

        /*for (Object item : lr.ArrayReservas) {
            lReservas.addElement(item);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventos = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btn_atras2 = new javax.swing.JButton();
        btn_sancionar = new javax.swing.JButton();
        btn_emparejar = new javax.swing.JButton();
        btn_ganador = new javax.swing.JButton();
        lbl_iniciosesion = new javax.swing.JLabel();
        botonesLuz = new javax.swing.ButtonGroup();
        descuento = new javax.swing.JInternalFrame();
        eldescuentoes = new javax.swing.JLabel();
        descuentoAct = new javax.swing.JLabel();
        xcien = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_administrar = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        scroll_parcelas = new javax.swing.JScrollPane();
        listaReservas = new javax.swing.JList<>();
        scroll_eventos = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        btn_descuento = new javax.swing.JButton();

        eventos.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        eventos.setTitle("Administrar Eventos");
        eventos.setLocation(new java.awt.Point(265, 112));
        eventos.setMinimumSize(new java.awt.Dimension(1000, 600));
        eventos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre Evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        jList2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "DNI1", "DNI2", "DNI3", "DNI4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        eventos.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 220, 270));

        btn_atras2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_atras2.setText("Atrás");
        btn_atras2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atras2ActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btn_atras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, 40));

        btn_sancionar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_sancionar.setText("Sancionar");
        btn_sancionar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_sancionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sancionarActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btn_sancionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 140, 40));

        btn_emparejar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_emparejar.setText("Emparejar");
        btn_emparejar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_emparejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emparejarActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btn_emparejar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 140, 40));

        btn_ganador.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_ganador.setText("Ganador");
        btn_ganador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ganadorActionPerformed(evt);
            }
        });
        eventos.getContentPane().add(btn_ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 140, 40));

        lbl_iniciosesion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_iniciosesion.setText("Seleccione un evento");
        eventos.getContentPane().add(lbl_iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 350, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descuento.setTitle("Descuento");
        descuento.setToolTipText("");
        descuento.setVisible(false);
        descuento.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eldescuentoes.setFont(jLabel1.getFont());
        eldescuentoes.setText("El descuento actual es de un");
        descuento.getContentPane().add(eldescuentoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 20));

        descuentoAct.setFont(jLabel1.getFont());
        descuentoAct.setText(" 0");
        descuento.getContentPane().add(descuentoAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 40, -1));

        xcien.setFont(jLabel1.getFont());
        xcien.setText("%.");
        descuento.getContentPane().add(xcien, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        atras.setFont(btn_atras.getFont());
        atras.setText("Atrás");
        atras.setBorder(btn_atras.getBorder());
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        descuento.getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 40));

        jButton1.setFont(atras.getFont());
        jButton1.setText("Actualizar");
        jButton1.setActionCommand("actualizarDescuento");
        jButton1.setBorder(atras.getBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        descuento.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 100, 40));

        jLabel1.setFont(eldescuentoes.getFont());
        jLabel1.setText("¿Desea actualizar el descuento?");
        descuento.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        getContentPane().add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 330, 250));

        btn_administrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_administrar.setText("Administrar");
        btn_administrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 110, 20));

        btn_atras.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_atras.setText("Atrás");
        btn_atras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, 40));

        btn_modificar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 90, 20));

        listaReservas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        listaReservas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Reserva 1", "Reserva 2", "Reserva 3", "Reserva 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scroll_parcelas.setViewportView(listaReservas);
        listaReservas.getAccessibleContext().setAccessibleName("Reservas");

        getContentPane().add(scroll_parcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, 210));

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eventos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Piscina", "Fronton", "Club Social" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scroll_eventos.setViewportView(jList3);

        getContentPane().add(scroll_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 170, 210));

        btn_descuento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_descuento.setText("Descuento");
        btn_descuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descuentoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administrarActionPerformed
        eventos.setSize(1000, 600);
        eventos.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_administrarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        this.setVisible(false);
        gestoresCamping = new GestoresCamping();
        VistaLogin vl = new VistaLogin(gestoresCamping);
        vl.setVisible(true);
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (listaReservas.getSelectedValue() != null) {
            this.setVisible(false);
            VistaActualizarReserva vap = new VistaActualizarReserva(gerente, vistaAnterior, listaReservas.getSelectedValue());
            vap.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una reserva.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atras2ActionPerformed
        eventos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btn_atras2ActionPerformed

    private void btn_sancionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sancionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sancionarActionPerformed

    private void btn_emparejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emparejarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_emparejarActionPerformed

    private void btn_ganadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ganadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ganadorActionPerformed

    private void btn_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descuentoActionPerformed
        descuento.setVisible(true);
    }//GEN-LAST:event_btn_descuentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        descuento.setVisible(false);
        descuentoAct.setText(JOptionPane.showInputDialog(null, "Introduce el descuento que quiere aplicar: ", "Descuento", JOptionPane.QUESTION_MESSAGE));
        if ("".equals(descuentoAct.getText())) {
            descuentoAct.setText(" 0");
        }
        gerente.setDescuento(Integer.parseInt(descuentoAct.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        descuento.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.ButtonGroup botonesLuz;
    private javax.swing.JButton btn_administrar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_atras2;
    private javax.swing.JButton btn_descuento;
    private javax.swing.JButton btn_emparejar;
    private javax.swing.JButton btn_ganador;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_sancionar;
    private javax.swing.JInternalFrame descuento;
    private javax.swing.JLabel descuentoAct;
    private javax.swing.JLabel eldescuentoes;
    private javax.swing.JFrame eventos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_iniciosesion;
    private javax.swing.JList<String> listaReservas;
    private javax.swing.JScrollPane scroll_eventos;
    private javax.swing.JScrollPane scroll_parcelas;
    private javax.swing.JLabel xcien;
    // End of variables declaration//GEN-END:variables
}
