/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Cliente;
import Controlador.UsuarioRegistrado;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
/**
 *
 * @author anita
 */
public class VistaClienteNuevaReserva extends javax.swing.JFrame {
    
    private JFrame vistaAnterior;
    private Cliente cliente;
    /**
     * Creates new form VistaNuevaReserva
     */
    VistaClienteNuevaReserva(Cliente cliente, VistaCliente v) {
        initComponents();
        this.vistaAnterior = v;
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapaParcelas = new javax.swing.JFrame();
        btn_cancelarMapa = new javax.swing.JButton();
        fondobotones10 = new javax.swing.JLabel();
        btn_guardarParcela = new javax.swing.JButton();
        fondobotones9 = new javax.swing.JLabel();
        p37 = new javax.swing.JRadioButton();
        p36 = new javax.swing.JRadioButton();
        p35 = new javax.swing.JRadioButton();
        p34 = new javax.swing.JRadioButton();
        p33 = new javax.swing.JRadioButton();
        p32 = new javax.swing.JRadioButton();
        p31 = new javax.swing.JRadioButton();
        p30 = new javax.swing.JRadioButton();
        p29 = new javax.swing.JRadioButton();
        p28 = new javax.swing.JRadioButton();
        p27 = new javax.swing.JRadioButton();
        p26 = new javax.swing.JRadioButton();
        p25 = new javax.swing.JRadioButton();
        p24 = new javax.swing.JRadioButton();
        p23 = new javax.swing.JRadioButton();
        p22 = new javax.swing.JRadioButton();
        p21 = new javax.swing.JRadioButton();
        p20 = new javax.swing.JRadioButton();
        p19 = new javax.swing.JRadioButton();
        p18 = new javax.swing.JRadioButton();
        p17 = new javax.swing.JRadioButton();
        p16 = new javax.swing.JRadioButton();
        p15 = new javax.swing.JRadioButton();
        p14 = new javax.swing.JRadioButton();
        p13 = new javax.swing.JRadioButton();
        p12 = new javax.swing.JRadioButton();
        p11 = new javax.swing.JRadioButton();
        p10 = new javax.swing.JRadioButton();
        p9 = new javax.swing.JRadioButton();
        p8 = new javax.swing.JRadioButton();
        p7 = new javax.swing.JRadioButton();
        p6 = new javax.swing.JRadioButton();
        p5 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p1 = new javax.swing.JRadioButton();
        lbl_mcuadrados = new javax.swing.JLabel();
        mTienda = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        tipoTienda = new javax.swing.JTextField();
        luzSi = new javax.swing.JRadioButton();
        luzNO = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_luzparcela = new javax.swing.JLabel();
        mapa = new javax.swing.JLabel();
        fondoVerde = new javax.swing.JLabel();
        fondoVerde1 = new javax.swing.JLabel();
        fondoVerde2 = new javax.swing.JLabel();
        grupo_botonesParcela = new javax.swing.ButtonGroup();
        grupo_botones_luz = new javax.swing.ButtonGroup();
        datoscliente = new javax.swing.JLabel();
        lbl_fechentrada = new javax.swing.JLabel();
        fEntrada = new datechooser.beans.DateChooserCombo();
        lbl_fechasalida = new javax.swing.JLabel();
        fSalida = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaParcelas = new javax.swing.JList<>();
        btn_seleccParcelas = new javax.swing.JButton();
        fondobotones6 = new javax.swing.JLabel();
        btn_finalizar = new javax.swing.JButton();
        fondobotones1 = new javax.swing.JLabel();
        btnPrincipalAtras = new javax.swing.JButton();
        fondobotones = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        mapaParcelas.setMinimumSize(new java.awt.Dimension(1000, 600));
        mapaParcelas.setSize(new java.awt.Dimension(1000, 600));
        mapaParcelas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cancelarMapa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cancelarMapa.setText("Cancelar");
        btn_cancelarMapa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cancelarMapa.setContentAreaFilled(false);
        btn_cancelarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarMapaActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(btn_cancelarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 200, 40));

        fondobotones10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones10.setText("jLabel2");
        mapaParcelas.getContentPane().add(fondobotones10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 200, 40));

        btn_guardarParcela.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_guardarParcela.setText("Guardar Parcela");
        btn_guardarParcela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_guardarParcela.setContentAreaFilled(false);
        btn_guardarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarParcelaActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(btn_guardarParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 200, 40));

        fondobotones9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones9.setText("jLabel2");
        mapaParcelas.getContentPane().add(fondobotones9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 200, 40));

        p37.setText("37");
        mapaParcelas.getContentPane().add(p37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 20, -1));

        p36.setText("36");
        mapaParcelas.getContentPane().add(p36, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 20, -1));

        p35.setText("35");
        mapaParcelas.getContentPane().add(p35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 20, -1));

        p34.setText("34");
        mapaParcelas.getContentPane().add(p34, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 20, -1));

        p33.setText("33");
        mapaParcelas.getContentPane().add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 20, -1));

        p32.setText("32");
        mapaParcelas.getContentPane().add(p32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 20, -1));

        p31.setText("31");
        p31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p31ActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(p31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 20, -1));

        p30.setText("30");
        mapaParcelas.getContentPane().add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 20, -1));

        p29.setText("29");
        mapaParcelas.getContentPane().add(p29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 20, -1));

        p28.setText("28");
        mapaParcelas.getContentPane().add(p28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 20, -1));

        p27.setText("27");
        mapaParcelas.getContentPane().add(p27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 20, -1));

        p26.setText("26");
        p26.setName(""); // NOI18N
        mapaParcelas.getContentPane().add(p26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 20, -1));

        p25.setText("25");
        mapaParcelas.getContentPane().add(p25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 20, -1));

        p24.setText("24");
        mapaParcelas.getContentPane().add(p24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 20, -1));

        p23.setText("23");
        p23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p23ActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(p23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 20, -1));

        p22.setText("22");
        mapaParcelas.getContentPane().add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 20, -1));

        p21.setText("21");
        mapaParcelas.getContentPane().add(p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 20, -1));

        p20.setText("20");
        mapaParcelas.getContentPane().add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 20, -1));

        p19.setText("19");
        mapaParcelas.getContentPane().add(p19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 20, -1));

        p18.setText("18");
        p18.setName("5"); // NOI18N
        mapaParcelas.getContentPane().add(p18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 20, -1));

        p17.setText("17");
        p17.setName("2"); // NOI18N
        mapaParcelas.getContentPane().add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 20, -1));

        p16.setText("16");
        p16.setName("4"); // NOI18N
        mapaParcelas.getContentPane().add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 20, -1));

        p15.setText("15");
        p15.setName("1"); // NOI18N
        mapaParcelas.getContentPane().add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 20, -1));

        p14.setText("14");
        p14.setName("3"); // NOI18N
        mapaParcelas.getContentPane().add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 20, -1));

        p13.setText("13");
        p13.setName("0"); // NOI18N
        mapaParcelas.getContentPane().add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 20, -1));

        p12.setText("12");
        mapaParcelas.getContentPane().add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 20, -1));

        p11.setText("11");
        mapaParcelas.getContentPane().add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 20, -1));

        p10.setText("10");
        mapaParcelas.getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 20, -1));

        p9.setText("9");
        mapaParcelas.getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 20, -1));

        p8.setText("8");
        mapaParcelas.getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 20, -1));

        p7.setText("7");
        mapaParcelas.getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 20, -1));

        p6.setText("6");
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 20, -1));

        p5.setText("5");
        mapaParcelas.getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 20, -1));

        p4.setText("4");
        mapaParcelas.getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 20, -1));

        p3.setText("3");
        mapaParcelas.getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 20, -1));

        p2.setText("2");
        p2.setName(""); // NOI18N
        mapaParcelas.getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 20, -1));

        p1.setText("1");
        p1.setName(""); // NOI18N
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 20, -1));

        lbl_mcuadrados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_mcuadrados.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mcuadrados.setText("Metros cuadrados:");
        mapaParcelas.getContentPane().add(lbl_mcuadrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        mTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTiendaActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(mTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 90, 30));

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");
        mapaParcelas.getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 30));

        tipoTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mapaParcelas.getContentPane().add(tipoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, 30));

        luzSi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luzSi.setForeground(new java.awt.Color(255, 255, 255));
        luzSi.setText("Si");
        luzSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzSiActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(luzSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 80, 30));

        luzNO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luzNO.setForeground(new java.awt.Color(255, 255, 255));
        luzNO.setText("No");
        luzNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzNOActionPerformed(evt);
            }
        });
        mapaParcelas.getContentPane().add(luzNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 90, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Introduzca los detalles de su tienda de campaña:");
        mapaParcelas.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 420, 40));

        lbl_luzparcela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_luzparcela.setForeground(new java.awt.Color(255, 255, 255));
        lbl_luzparcela.setText("¿Desea contar con servicio de luz en su parcela ?");
        mapaParcelas.getContentPane().add(lbl_luzparcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 410, 30));

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mapa.png"))); // NOI18N
        mapa.setOpaque(true);
        mapaParcelas.getContentPane().add(mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        fondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoverde.png"))); // NOI18N
        mapaParcelas.getContentPane().add(fondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 70, -1, -1));

        fondoVerde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoverde.png"))); // NOI18N
        mapaParcelas.getContentPane().add(fondoVerde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        fondoVerde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoverde.png"))); // NOI18N
        mapaParcelas.getContentPane().add(fondoVerde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datoscliente.setFont(new java.awt.Font("Georgia Pro", 0, 24)); // NOI18N
        datoscliente.setText("Nueva Reserva");
        getContentPane().add(datoscliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 170, 40));

        lbl_fechentrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechentrada.setText("Fecha de entrada:");
        getContentPane().add(lbl_fechentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 150, 40));

        fEntrada.setCalendarPreferredSize(new java.awt.Dimension(317, 321));
        getContentPane().add(fEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 190, 40));

        lbl_fechasalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechasalida.setText("Fecha de salida:");
        getContentPane().add(lbl_fechasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, 40));
        getContentPane().add(fSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 190, 40));

        listaParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mis parcelas reservadas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        listaParcelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listaParcelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaParcelas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 360, 150));

        btn_seleccParcelas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_seleccParcelas.setText("Seleccionar Parcela");
        btn_seleccParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_seleccParcelas.setContentAreaFilled(false);
        btn_seleccParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccParcelasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seleccParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 200, 40));

        fondobotones6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones6.setText("jLabel2");
        getContentPane().add(fondobotones6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 200, 40));

        btn_finalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_finalizar.setText("Finalizar");
        btn_finalizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_finalizar.setContentAreaFilled(false);
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 130, 40));

        fondobotones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones1.setText("jLabel2");
        getContentPane().add(fondobotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 130, 40));

        btnPrincipalAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipalAtras.setText("Atras");
        btnPrincipalAtras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPrincipalAtras.setContentAreaFilled(false);
        btnPrincipalAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrincipalAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 130, 40));

        fondobotones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blancoroto.jpg"))); // NOI18N
        fondobotones.setText("jLabel2");
        getContentPane().add(fondobotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoazulconcamping.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccParcelasActionPerformed
        this.setVisible(false);
        mapaParcelas.setVisible(true);
    }//GEN-LAST:event_btn_seleccParcelasActionPerformed

    private void btn_cancelarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarMapaActionPerformed
        this.setVisible(true);
        mapaParcelas.setVisible(false);
        tipoTienda.setText("");
        mTienda.setText("");
        grupo_botonesParcela.clearSelection();
        grupo_botones_luz.clearSelection();
    }//GEN-LAST:event_btn_cancelarMapaActionPerformed

    private void btn_guardarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarParcelaActionPerformed
        try{

            boolean encontrado = false;
            Enumeration botones = grupo_botonesParcela.getElements();
            JRadioButton botonSeleccionado = new JRadioButton();
            while (botones.hasMoreElements() && !encontrado){
                botonSeleccionado = (JRadioButton)botones.nextElement();
                if(botonSeleccionado.isSelected()){
                    encontrado = true;
                }
            }
            /*Object parcela = cli.devolverParcela(Integer.parseInt(botonSeleccionado.getText()));
            if(cli.tamanyoCorrecto(parcela, Integer.parseInt(mTienda.getText()))){
                // Guardamos la parcela en un arraylist de parcelas seleccionadas
                parcelasSeleccionadas.add(parcela);
                lParcelas.addElement(parcela);
                listaParcelas.updateUI();

                // Guardamos los datos de la tienda de campaña seleccionada
                nombresTiendas.add(tipoTienda.getText());
                metrosTiendas.add(Integer.parseInt(mTienda.getText()));

                //Comprobamos si quiere luz en esa parcela o no
                if (luzSi.isSelected()) {
                    luzParcelas.add(true);
                }else{
                    luzParcelas.add(false);
                }

                // Dejamos la vista en un estado para que se pueda seleccionar otra parcela
                // Borramos el contenido de los text field
                tipoTienda.setText("");
                mTienda.setText("");

                // Hacemos que no se pueda volver a seleccionar la tienda actual y
                // quitamos la seleccion de todos los grupos de botones
                botonSeleccionado.setEnabled(false);
                grupo_botonesParcela.clearSelection();
                grupo_botones_luz.clearSelection();

                // Ocultamos la ventana para seleccionar parcelas
                this.setVisible(true);
                mapaParcelas.setVisible(false);
                btn_finalizar.setVisible(true);
                fondobotones7.setVisible(true);
            } else{
                JOptionPane.showMessageDialog(this, "El tamanyo de la tienda es mayor al de la parcela seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
            }*/

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en alguno de los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_guardarParcelaActionPerformed

    private void p31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p31ActionPerformed

    }//GEN-LAST:event_p31ActionPerformed

    private void p23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p23ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed

    }//GEN-LAST:event_p6ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed

    }//GEN-LAST:event_p1ActionPerformed

    private void mTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTiendaActionPerformed

    private void luzSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzSiActionPerformed

    private void luzNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzNOActionPerformed

    private void btnPrincipalAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalAtrasActionPerformed
        vistaAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPrincipalAtrasActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        try {
            // Damos de alta el cliente en caso de que no este dado de alta
            /*if (this.cliente == null) {
                cliente = noRegistrado.altaCliente(txt_dni.getText(), String.valueOf(txt_contra.getPassword()),
                    nombreyApellidos.getText(), txt_tel.getText(), txt_correo.getText(), txt_cp.getText());
            }

            // Nos guardamos las fechas de entrada y salida del cliente
            Date fechaIni = fEntrada.getSelectedDate().getTime();
            Date fechaFin = fSalida.getSelectedDate().getTime();

            // Hacemos la reserva
            cliente.realizarReserva(nombresTiendas, metrosTiendas, luzParcelas, parcelasSeleccionadas, fechaIni, fechaFin);
            
            vistaAnterior.setVisible(true);
            this.setVisible(false);*/

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en alguno de los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VistaClienteNuevaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrincipalAtras;
    private javax.swing.JButton btn_cancelarMapa;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_guardarParcela;
    private javax.swing.JButton btn_seleccParcelas;
    private javax.swing.JLabel datoscliente;
    private datechooser.beans.DateChooserCombo fEntrada;
    private datechooser.beans.DateChooserCombo fSalida;
    private javax.swing.JLabel fondoVerde;
    private javax.swing.JLabel fondoVerde1;
    private javax.swing.JLabel fondoVerde2;
    private javax.swing.JLabel fondobotones;
    private javax.swing.JLabel fondobotones1;
    private javax.swing.JLabel fondobotones10;
    private javax.swing.JLabel fondobotones6;
    private javax.swing.JLabel fondobotones9;
    private javax.swing.ButtonGroup grupo_botonesParcela;
    private javax.swing.ButtonGroup grupo_botones_luz;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fechasalida;
    private javax.swing.JLabel lbl_fechentrada;
    private javax.swing.JLabel lbl_luzparcela;
    private javax.swing.JLabel lbl_mcuadrados;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JList<Object> listaParcelas;
    private javax.swing.JRadioButton luzNO;
    private javax.swing.JRadioButton luzSi;
    private javax.swing.JTextField mTienda;
    private javax.swing.JLabel mapa;
    private javax.swing.JFrame mapaParcelas;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p10;
    private javax.swing.JRadioButton p11;
    private javax.swing.JRadioButton p12;
    private javax.swing.JRadioButton p13;
    private javax.swing.JRadioButton p14;
    private javax.swing.JRadioButton p15;
    private javax.swing.JRadioButton p16;
    private javax.swing.JRadioButton p17;
    private javax.swing.JRadioButton p18;
    private javax.swing.JRadioButton p19;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p20;
    private javax.swing.JRadioButton p21;
    private javax.swing.JRadioButton p22;
    private javax.swing.JRadioButton p23;
    private javax.swing.JRadioButton p24;
    private javax.swing.JRadioButton p25;
    private javax.swing.JRadioButton p26;
    private javax.swing.JRadioButton p27;
    private javax.swing.JRadioButton p28;
    private javax.swing.JRadioButton p29;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p30;
    private javax.swing.JRadioButton p31;
    private javax.swing.JRadioButton p32;
    private javax.swing.JRadioButton p33;
    private javax.swing.JRadioButton p34;
    private javax.swing.JRadioButton p35;
    private javax.swing.JRadioButton p36;
    private javax.swing.JRadioButton p37;
    private javax.swing.JRadioButton p4;
    private javax.swing.JRadioButton p5;
    private javax.swing.JRadioButton p6;
    private javax.swing.JRadioButton p7;
    private javax.swing.JRadioButton p8;
    private javax.swing.JRadioButton p9;
    private javax.swing.JTextField tipoTienda;
    // End of variables declaration//GEN-END:variables
}
