/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacioncamping;

import javax.swing.JComboBox;

/**
 *
 * @author antho
 */
public class Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    
    String Item = "";
    
    public Reserva() {
        
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Reservas");
        
        //Seleccion del radioButton de la Luz
        grupo_botones_luz.add(luzSi);
        grupo_botones_luz.add(luzNO);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        grupo_botones_luz = new javax.swing.ButtonGroup();
        lbl_nomape = new javax.swing.JLabel();
        nombreyApellidos = new javax.swing.JTextField();
        lbl_dni = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        lbl_numparcel = new javax.swing.JLabel();
        cb_nParcelas = new javax.swing.JComboBox<>();
        lbl_fechentrada = new javax.swing.JLabel();
        fEntrada = new datechooser.beans.DateChooserCombo();
        lbl_fechasalida = new javax.swing.JLabel();
        fSalida = new datechooser.beans.DateChooserCombo();
        lbl_mcuadrados = new javax.swing.JLabel();
        mTienda = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        tipoTienda = new javax.swing.JTextField();
        luzSi = new javax.swing.JRadioButton();
        luzNO = new javax.swing.JRadioButton();
        btn_confirmareserva = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_luzparcela = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nomape.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nomape.setText("Nombre y Apellidos:");
        getContentPane().add(lbl_nomape, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 30));

        nombreyApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreyApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreyApellidos.setOpaque(false);
        getContentPane().add(nombreyApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 30));

        lbl_dni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_dni.setText("DNI:");
        getContentPane().add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 50, 30));

        DNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DNI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DNI.setOpaque(false);
        getContentPane().add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, 30));

        lbl_numparcel.setFont(jLabel10.getFont());
        lbl_numparcel.setText("Nº de parcelas:");
        getContentPane().add(lbl_numparcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 130, 30));

        cb_nParcelas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_nParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Una", "Dos", "Tres", "Cuatro" }));
        cb_nParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nParcelasActionPerformed(evt);
            }
        });
        getContentPane().add(cb_nParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 90, 30));

        lbl_fechentrada.setFont(jLabel10.getFont());
        lbl_fechentrada.setText("Fecha de entrada:");
        getContentPane().add(lbl_fechentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 150, 30));

        fEntrada.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        getContentPane().add(fEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, 30));

        lbl_fechasalida.setFont(jLabel10.getFont());
        lbl_fechasalida.setText("Fecha de salida:");
        getContentPane().add(lbl_fechasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 140, 30));

        fSalida.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        getContentPane().add(fSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, 30));

        lbl_mcuadrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_mcuadrados.setText("Metros cuadrados:");
        getContentPane().add(lbl_mcuadrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 160, 30));

        mTienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mTienda.setOpaque(false);
        getContentPane().add(mTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 150, 30));

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, 30));

        tipoTienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tipoTienda.setOpaque(false);
        getContentPane().add(tipoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 30));

        luzSi.setFont(jLabel10.getFont());
        luzSi.setText("Si");
        getContentPane().add(luzSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 80, -1));

        luzNO.setFont(jLabel10.getFont());
        luzNO.setText("No");
        luzNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzNOActionPerformed(evt);
            }
        });
        getContentPane().add(luzNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 90, -1));

        btn_confirmareserva.setFont(jLabel10.getFont());
        btn_confirmareserva.setText("Confirmar reserva");
        btn_confirmareserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmareservaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirmareserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 180, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Introduzca sus datos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 40));

        jLabel9.setFont(jLabel10.getFont());
        jLabel9.setText("Datos de la reserva:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 160, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Introduzca los detalles de su tienda de campaña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 460, 20));

        lbl_luzparcela.setFont(jLabel10.getFont());
        lbl_luzparcela.setText("¿Desea contar con servicio de luz en su parcela ?");
        getContentPane().add(lbl_luzparcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 410, 20));

        btn_cancelar.setFont(jLabel10.getFont());
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 140, 40));

        btn_aceptar.setFont(jLabel10.getFont());
        btn_aceptar.setText("Aceptar");
        btn_aceptar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luzNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzNOActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
        Principal prin = new Principal();
        prin.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void cb_nParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nParcelasActionPerformed
        
    }//GEN-LAST:event_cb_nParcelasActionPerformed

    private void btn_confirmareservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmareservaActionPerformed
        String Item = cb_nParcelas.getSelectedItem().toString();
        
        
    }//GEN-LAST:event_btn_confirmareservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNI;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmareserva;
    private javax.swing.JComboBox<String> cb_nParcelas;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserCombo fEntrada;
    private datechooser.beans.DateChooserCombo fSalida;
    private javax.swing.ButtonGroup grupo_botones_luz;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fechasalida;
    private javax.swing.JLabel lbl_fechentrada;
    private javax.swing.JLabel lbl_luzparcela;
    private javax.swing.JLabel lbl_mcuadrados;
    private javax.swing.JLabel lbl_nomape;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numparcel;
    private javax.swing.JRadioButton luzNO;
    private javax.swing.JRadioButton luzSi;
    private javax.swing.JTextField mTienda;
    private javax.swing.JTextField nombreyApellidos;
    private javax.swing.JTextField tipoTienda;
    // End of variables declaration//GEN-END:variables
}
