/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacioncamping;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author anita
 */
public class SinReserva extends javax.swing.JFrame {

    /**
     * Creates new form Alquiler
     */
    
    String Item = "";
    
    public SinReserva() {

        initComponents();
        setLocationRelativeTo(null);

        this.setTitle("Sin Reserva");
        
        //Seleccion del radioButton de la Luz
        grupo_botones_luz.add(luzSi);
        grupo_botones_luz.add(luzNO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones_luz = new javax.swing.ButtonGroup();
        lbl_mcuadrados = new javax.swing.JLabel();
        lbl_nomape = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        lbl_fechsalida = new javax.swing.JLabel();
        lbl_numparcel = new javax.swing.JLabel();
        lbl_luz = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_detalles = new javax.swing.JLabel();
        txt_metrosTienda = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        txt_tienda = new javax.swing.JTextField();
        txt_nombreApellidos = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        luzSi = new javax.swing.JRadioButton();
        luzNO = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        nparcelas = new javax.swing.JSpinner();
        lbl_numparcel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_mcuadrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_mcuadrados.setText("Metros cuadrados:");
        getContentPane().add(lbl_mcuadrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 360, 160, 20));

        lbl_nomape.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nomape.setText("Nombre y Apellidos:");
        getContentPane().add(lbl_nomape, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 90, 180, 20));

        lbl_dni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_dni.setText("DNI:");
        getContentPane().add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 130, 50, 20));

        lbl_fechsalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fechsalida.setText("Fecha de salida:");
        getContentPane().add(lbl_fechsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 140, 20));

        lbl_numparcel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_numparcel.setText("Nº de Parcelas:");
        getContentPane().add(lbl_numparcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, 20));

        lbl_luz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_luz.setText("¿Desea contar con servicio de luz en la parcela?");
        getContentPane().add(lbl_luz, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 420, 400, 40));

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 320, 80, 20));

        lbl_detalles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_detalles.setText("Introduzca los detalles de su tienda de campaña:");
        getContentPane().add(lbl_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 270, 410, 20));

        txt_metrosTienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_metrosTienda.setToolTipText("");
        txt_metrosTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_metrosTienda.setOpaque(false);
        txt_metrosTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_metrosTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_metrosTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 150, -1));

        txt_DNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_DNI.setToolTipText("");
        txt_DNI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DNI.setOpaque(false);
        txt_DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DNIActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, -1));

        txt_tienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tienda.setToolTipText("");
        txt_tienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_tienda.setOpaque(false);
        txt_tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tiendaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 150, -1));

        txt_nombreApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_nombreApellidos.setToolTipText("");
        txt_nombreApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_nombreApellidos.setOpaque(false);
        txt_nombreApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, -1));

        dateChooserCombo1.setFieldFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        getContentPane().add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 140, 40));

        btn_aceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 140, 40));

        luzSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luzSi.setText("Si");
        getContentPane().add(luzSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 80, -1));

        luzNO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luzNO.setText("No");
        luzNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzNOActionPerformed(evt);
            }
        });
        getContentPane().add(luzNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Introduzca sus datos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 200, 40));

        nparcelas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nparcelas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        nparcelas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nparcelasStateChanged(evt);
            }
        });
        getContentPane().add(nparcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 60, 30));

        lbl_numparcel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_numparcel1.setText("20 metros por parcela");
        getContentPane().add(lbl_numparcel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 74, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_metrosTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_metrosTiendaActionPerformed
        
    }//GEN-LAST:event_txt_metrosTiendaActionPerformed

    private void txt_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DNIActionPerformed

    private void txt_tiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tiendaActionPerformed

    private void txt_nombreApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreApellidosActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
        Principal pri = new Principal();
        pri.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        int mtienda = Integer.parseInt(txt_metrosTienda.getText());
        int mparcelas = (Integer)nparcelas.getValue() * 20;
        
        if ( (mparcelas - mtienda) >= 0 ){
            //Sr guarda y cerramos 
        }
        else
            JOptionPane.showMessageDialog(new JFrame(), "La tienda excede los "
                    + "metrso de las parcelas seleccionadas.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void luzNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzNOActionPerformed

    private void nparcelasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nparcelasStateChanged
        
    }//GEN-LAST:event_nparcelasStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.ButtonGroup grupo_botones_luz;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_detalles;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fechsalida;
    private javax.swing.JLabel lbl_luz;
    private javax.swing.JLabel lbl_mcuadrados;
    private javax.swing.JLabel lbl_nomape;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numparcel;
    private javax.swing.JLabel lbl_numparcel1;
    private javax.swing.JRadioButton luzNO;
    private javax.swing.JRadioButton luzSi;
    private javax.swing.JSpinner nparcelas;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_metrosTienda;
    private javax.swing.JTextField txt_nombreApellidos;
    private javax.swing.JTextField txt_tienda;
    // End of variables declaration//GEN-END:variables
}
